install.packages(c('IRkernel', 'fastR2', 'fivethirtyeight', 'janitor', 'lubridate', 'mosaic', 'openintro', 'patchwork', 'scales', 'skimr', 'tidyverse'),repos='http://cran.us.r-project.org')
install.packages(c('plotly', 'sf', 'here', 'tabula', 'here', 'ggbeeswarm', 'cowplot', 'ggtext', 'raster', 'terra', 'spatstat', 'maptools', 'RColorBrewer', 'viridis', 'wesanderson', 'rcarbon', 'ggridges', 'ggrepel', 'visdat', 'igraph', 'statnet', 'gapminder'), repos='https://cran.rstudio.com')
install.packages('fivethirtyeightdata', repos='https://fivethirtyeightdata.github.io/drat/', type='source')
devtools::install_github(c('rstudio-education/dsbox'))
devtools::install_github('IRkernel/repr', ref = 'master')
IRkernel::installspec()
